GET http://localhost:3000

###

GET http://localhost:3000/ping

###

POST /v1/getBalance HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "UserId": 1
}

###

POST http://0.0.0.0:3000/v1/addBalance
Content-Type: application/json

{
  "UserId": 1,
  "Balance": 10
}

###

POST http://localhost:3000/v1/reserveFunds
Content-Type: application/json

{
  "UserId": 1,
  "ServiceId": 1,
  "OrderServiceId": 1,
  "ReserveBalance": 10
}

###

POST http://localhost:3000/v1/acceptProfit
Content-Type: application/json

{
  "UserId": 1,
  "ServiceId":1,
  "OrderServiceId": 1,
  "ReserveBalance": 10
}